import cafe from "./holidayActivityAssets/cafe.svg"
import camp from "./holidayActivityAssets/camp.svg"
import chilling from "./holidayActivityAssets/chilling.svg"
import diy from "./holidayActivityAssets/diy.svg"
import drinking from "./holidayActivityAssets/drinking.svg"
import driving from "./holidayActivityAssets/drive.svg"
import food from "./holidayActivityAssets/food.svg"
import football from "./holidayActivityAssets/football.svg"
import game from "./holidayActivityAssets/game-controll.svg"
import golf from "./holidayActivityAssets/golf.svg"
import guitar from "./holidayActivityAssets/guitar.svg"
import gym from "./holidayActivityAssets/gym.svg"
import hiking from "./holidayActivityAssets/hiking.svg"
import karaoke from "./holidayActivityAssets/karaoke.svg"
import live from "./holidayActivityAssets/live-event.svg"
import music from "./holidayActivityAssets/music.svg"
import netflix from "./holidayActivityAssets/netflix.svg"
import running from "./holidayActivityAssets/person-running.svg"
import pets from "./holidayActivityAssets/pets.svg"
import shopping from "./holidayActivityAssets/shopping.svg"
import swimming from "./holidayActivityAssets/swim.svg"
import theatre from "./holidayActivityAssets/theatre.svg"
import travel from "./holidayActivityAssets/travel.svg"
import voleenter from "./holidayActivityAssets/voleenter.svg"
import yoga from "./holidayActivityAssets/yoga.svg"
import youtube from "./holidayActivityAssets/youtube.svg"

export { cafe, camp, chilling, diy, drinking, driving, food, football, game, golf, guitar, gym, hiking, karaoke, live, music, netflix, pets, running, shopping, swimming, theatre, travel, voleenter, yoga, youtube }

